<?php

namespace Liip\DataAggregatorBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EntityBossRepository
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityBossRepository extends EntityRepository
{
}
